name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci # 相当于npm install
    - run: npm run build
    - run: echo 'fe.const.team' > CNAME

    #发布到mybells.github.io/master
    - name: Deploy EG-FE.github.io/master
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
        EXTERNAL_REPOSITORY: EG-FE/EG-FE.github.io 
        PUBLISH_BRANCH: master
        PUBLISH_DIR: docs/.vuepress/dist
      with:
          emptyCommits: false